[project]
name = "voice-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "livekit-agents>=1.7.0",
    "livekit-plugins-google>=1.7.0",
    "livekit-plugins-groq>=1.7.0",
    "livekit-plugins-noise-cancellation>=0.3.0",
    "livekit-plugins-silero>=1.7.0",
    "local-livekit-plugins",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "streamlit>=1.62.0",
]

[tool.uv.sources]
local-livekit-plugins = { git = "https://github.com/CoreWorxLab/local-livekit-plugins.git" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
